version: '3'
services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - keep_up_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: keepUp
  keepupapi:
    build: ./keepUpAPI
    ports:
      - "4000:4000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: keepUp
      DB_HOST: db
    depends_on:
      - db
  keepupapp:
    build: ./keepUpApp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - keepupapi

volumes:
  keep_up_db_data: {}

