services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - omnimor_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
      
  omnimorapi:
    image: omnimorapi:latest
    ports:
      - "4000:4000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
      DB_HOST: db
      API_PORT: 4000
    depends_on:
      db:
        condition: service_healthy

  omnimorapp:
    image: omnimorapp:latest
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
    depends_on:
      - omnimorapi

volumes:
  omnimor_db_data: {}

